export const mockClasses = [
  {
    id: '1',
    name: 'English Group',
    type: 'course',
    level: 'A1 → A2',
    schedule: 'Tue & Fri, 18:30',
    meetingUrl: null,
    inviteCode: 'TRA1QX',
    enrollmentOpen: true,
    isActive: true,
    studentCount: 4,
  },
  {
    id: '2',
    name: 'Conversation Club',
    type: 'conversation',
    level: null,
    schedule: 'Sundays, 11:00',
    meetingUrl: null,
    inviteCode: 'SOHBET',
    enrollmentOpen: true,
    isActive: true,
    studentCount: 24,
  },
  {
    id: '3',
    name: 'Laman Lara',
    type: 'one_to_one',
    level: 'B1',
    schedule: 'Wed, Sat & Sun, 18:00',
    meetingUrl: 'https://meet.google.com/uqy-jrgj-zse',
    inviteCode: 'LL9TR7',
    enrollmentOpen: false,
    isActive: true,
    studentCount: 1,
  },
  {
    id: '4',
    name: 'Jasmin Gieve',
    type: 'one_to_one',
    level: 'B1',
    schedule: 'Mon & Thu, 18:00',
    meetingUrl: 'https://meet.google.com/uqy-jrgj-zse',
    inviteCode: 'JS7TR1',
    enrollmentOpen: false,
    isActive: true,
    studentCount: 1,
  },
  {
    id: '5',
    name: 'Guyla Yvoserv',
    type: 'one_to_one',
    level: 'B1',
    schedule: 'Mon & Fri, 18:00',
    meetingUrl: 'https://meet.google.com/uqy-jrgj-zse',
    inviteCode: 'GY5T79',
    enrollmentOpen: false,
    isActive: true,
    studentCount: 1,
  },
];
