export const mockClasses: ClassWithCount[] = [
  {
    id: '1',
    teacherId: 't1',
    name: 'English Group',
    type: 'course',
    level: 'elementary',
    schedule: 'Tue & Fri, 18:30',
    meetingUrl: null,
    inviteCode: 'TRA1QX',
    handlesPayment: false,
    enrollmentOpen: true,
    isActive: true,
    createdAt: '2026-08-20T10:00:00Z',
    studentCount: 4,
  },
  {
    id: '2',
    teacherId: 't1',
    name: 'Conversation Club',
    type: 'conversation',
    level: null,
    schedule: 'Sundays, 11:00',
    meetingUrl: null,
    inviteCode: 'SOHBET',
    handlesPayment: false,
    enrollmentOpen: true,
    isActive: true,
    createdAt: '2026-08-20T10:00:00Z',
    studentCount: 24,
  },
  {
    id: '3',
    teacherId: 't1',
    name: 'Laman Lara',
    type: 'one_to_one',
    level: 'intermediate',
    schedule: 'Wed, Sat & Sun, 18:00',
    meetingUrl: 'https://meet.google.com/uqy-jrgj-zse',
    inviteCode: 'LL9TR7',
    handlesPayment: true,
    enrollmentOpen: false,
    isActive: true,
    createdAt: '2026-08-22T10:00:00Z',
    studentCount: 1,
  },
  {
    id: '4',
    teacherId: 't1',
    name: 'Jasmin Gieve',
    type: 'one_to_one',
    level: 'intermediate',
    schedule: 'Mon & Thu, 18:00',
    meetingUrl: 'https://meet.google.com/uqy-jrgj-zse',
    inviteCode: 'JS7TR1',
    handlesPayment: true,
    enrollmentOpen: false,
    isActive: true,
    createdAt: '2026-08-25T10:00:00Z',
    studentCount: 1,
  },
  {
    id: '5',
    teacherId: 't1',
    name: 'Guyla Yvoserv',
    type: 'one_to_one',
    level: 'intermediate',
    schedule: 'Mon & Fri, 18:00',
    meetingUrl: 'https://meet.google.com/uqy-jrgj-zse',
    inviteCode: 'GY5T79',
    handlesPayment: true,
    enrollmentOpen: false,
    isActive: true,
    createdAt: '2026-08-28T10:00:00Z',
    studentCount: 1,
  },
];
