export const mockhomeWorks: HomeWorkWithSubmission[] = [
  {
    id: 'a1',
    classId: '1',
    title: 'Past simple worksheet',
    instructions: null,
    attachmentPath: '/uploads/past-simple-worksheet.pdf',
    dueDate: null,
    isPublished: true,
    createdAt: '2026-09-08T10:00:00Z',
    submission: null,
  },
  {
    id: 'a2',
    classId: '1',
    title: 'Present perfect practice',
    instructions: null,
    attachmentPath: '/uploads/present-perfect.pdf',
    dueDate: null,
    isPublished: true,
    createdAt: '2026-09-01T10:00:00Z',
    submission: null,
  },
  {
    id: 'a3',
    classId: '3',
    title: 'Describing your week',
    instructions: 'Write 150 words about your week. Use the past simple.',
    attachmentPath: '/uploads/describing-your-week.pdf',
    dueDate: '2026-09-13T18:00:00Z',
    isPublished: true,
    createdAt: '2026-09-09T09:00:00Z',
    submission: {
      submittedAt: '2026-09-12T20:14:00Z',
      reviewedAt: null,
    },
  },
  {
    id: 'a4',
    classId: '4',
    title: 'Job interview vocabulary',
    instructions: null,
    attachmentPath: '/uploads/interview-vocab.pdf',
    dueDate: '2026-09-11T18:00:00Z',
    isPublished: true,
    createdAt: '2026-09-07T09:00:00Z',
    submission: null,
  },
];
