export const mockMaterials: MaterialRecord[] = [
  {
    id: 'm1',
    classId: null,
    title: 'BBC Learning English: 6 Minute English',
    description:
      'Short podcast episodes on everyday topics. Good for listening practice on the bus.',
    kind: 'link',
    filePath: null,
    url: 'https://www.youtube.com/watch?v=FrRSqYYzBlk&t=659s',
    level: null,
    uploadedAt: '2026-09-10T09:00:00Z',
  },
  {
    id: 'm2',
    classId: null,
    title: 'Irregular verbs reference sheet',
    description: 'Print this and keep it in your notebook.',
    kind: 'file',
    filePath: '/uploads/irregular-verbs.pdf',
    url: null,
    level: 'beginner',
    uploadedAt: '2026-09-08T14:00:00Z',
  },
  {
    id: 'm3',
    classId: null,
    title: 'How to describe your job in English',
    description: null,
    kind: 'link',
    filePath: null,
    url: 'https://www.youtube.com/watch?v=FrRSqYYzBlk&t=659s',
    level: 'elementary',
    uploadedAt: '2026-09-05T11:00:00Z',
  },
  {
    id: 'm4',
    classId: null,
    title: 'Phrasal verbs for conversation',
    description:
      'Fifty common phrasal verbs with example sentences. Useful before Sunday club.',
    kind: 'file',
    filePath: '/uploads/phrasal-verbs.pdf',
    url: null,
    level: 'intermediate',
    uploadedAt: '2026-09-02T16:00:00Z',
  },
  {
    id: 'm5',
    classId: null,
    title: 'Reading: short stories in simple English',
    description: null,
    kind: 'link',
    filePath: null,
    url: 'https://www.youtube.com/watch?v=FrRSqYYzBlk&t=659s',
    level: 'advanced',
    uploadedAt: '2026-08-28T10:00:00Z',
  },
  {
    id: 'm6',
    classId: null,
    title: 'Reading: short stories in simple English',
    description: null,
    kind: 'link',
    filePath: null,
    url: 'https://www.youtube.com/watch?v=FrRSqYYzBlk&t=659s',
    level: 'advanced',
    uploadedAt: '2026-08-28T10:00:00Z',
  },
];
